services:
  db:
    image: postgres:17.4
    container_name: temp-db
    restart: always
    secrets:
      - db_username
      - db_password
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_username
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB=sensorsdata
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:

secrets:
  db_username:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt

